apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
spec:
  selector:
      matchLabels:
        app: chatapp
  replicas: 3
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
        - name: chatapp
          #image: bjnmc/chatapp:configActuator
          image: bjnmc/chatapp:rabbit
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
              # httpHeaders:
              # - name: Custom-Header
              #   value: Awesome
            # initialDelaySeconds: 3
            # periodSeconds: 3
          env:
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config  
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config 
                  key: host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config 
                  key: port
            - name: MONGO_AUTH
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config 
                  key: auth
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k8-training
                  key:  MONGO_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8-training
                  key:  MONGO_ROOT_PASSWORD
            ## For RabbitMQ
            - name: RABBITMQ_HOST
              valueFrom: 
                secretKeyRef: 
                  name: stomp-messagebroker-default-user
                  key: host
            - name: RABBITMQ_USERNAME
              valueFrom: 
                secretKeyRef: 
                  name: stomp-messagebroker-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: stomp-messagebroker-default-user
                  key: password
                  