apiVersion: v1
kind: Service
metadata:
  name: chatapp
spec:
  selector:
    app: chatapp
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

  ### This waits for `minikube tunnel` and then it will display the external ip