apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: stomp-messagebroker
spec:
  image: rabbitmq:3.9.9-management
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_stomp
      - rabbitmq_web_stomp