apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongo #this is the host name which is used by the chatapp to connect to mongoDB
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  clusterIP: None
